### ISSUE TITLE
AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by AnudeepGarge** [somdoron/AsyncIO#34]
Hi,

 I am using Dealer-Broker pattern in NetMQ (4.0.0.1), ASyncIO(0.1.26.0)
I can see some AccessViolationException in my UnHandledException logs, Not Sure where it is coming from. I am suspecting that the issue is happening during dealer creation.

CALL STACK OF EXCEPTION AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
ExceptionServices(Kernal.Common):    at AsyncIO.Windows.Overlapped.get_Success()
ExceptionServices(Kernal.Common):    at AsyncIO.Windows.CompletionPort.HandleCompletionStatus(CompletionStatus& completionStatus, IntPtr overlappedAddress, IntPtr completionKey, Int32 bytesTransferred)
ExceptionServices(Kernal.Common):    at AsyncIO.Windows.CompletionPort.GetMultipleQueuedCompletionStatus(Int32 timeout, CompletionStatus[] completionStatuses, Int32& removed)
ExceptionServices(Kernal.Common):    at NetMQ.Core.Utils.Proactor.Loop()
ExceptionServices(Kernal.Common):    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
ExceptionServices(Kernal.Common):    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
ExceptionServices(Kernal.Common):    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
ExceptionServices(Kernal.Common):    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
ExceptionServices(Kernal.Common):    at System.Threading.ThreadHelper.ThreadStart()

**Comment by somdoron** [comment]
Which version of AsyncIO?

**Comment by somdoron** [comment]
Can you try the latest version of AsyncIO?
probably already solved.

**Comment by AnudeepGarge** [comment]
Thanks for the quick replay @somdoron . I will try with latest version.
