### ISSUE TITLE
PlatformNotSupportedException on Linux

### ISSUE THREAD

**Issue by Svisstack** [somdoron/AsyncIO#36]
Having an indirect problem with this library. Does it work outside the Window?

```
[14:21:05 FTL] Unhandled exception
System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.
   at System.Net.Sockets.SocketPal.WindowsIoctl(SafeSocketHandle handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at System.Net.Sockets.Socket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at AsyncIO.DotNet.NativeSocket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
```

**Comment by Svisstack** [comment]
Related https://github.com/zeromq/netmq/issues/846

**Comment by somdoron** [comment]
Yes, which OS?

**Comment by Svisstack** [comment]
@somdoron Appreciate the fast response on this one as this blocked me hard. I confirm that without KeepAlive works correctly.
